# Generated by Django 4.2.9 on 2024-02-11 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_workplace_delete_name_employee_workplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeNo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=5, verbose_name="従業員番号")),
                (
                    "created_by",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="日付"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="employeeno",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="従業員番号"
            ),
        ),
    ]
