# Generated by Django 4.2.9 on 2024-02-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_employeeno_employee_employeeno"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeNo",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employeeno",
        ),
    ]
