# Generated by Django 4.2.9 on 2024-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0005_delete_employeeno_remove_employee_employeeno"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user_name",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ユーザーネーム"
            ),
        ),
    ]
