# Generated by Django 4.2.9 on 2024-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_attendance_staff_alter_attendance_in_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="in_out",
            field=models.IntegerField(
                choices=[(1, "IN"), (0, "OUT")], default=None, verbose_name="IN/OUT"
            ),
        ),
    ]
