# Generated by Django 4.2.9 on 2024-02-11 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0003_alter_attendance_in_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="staff",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="従業員",
            ),
        ),
        migrations.AlterModelTable(
            name="attendance",
            table="attendance",
        ),
    ]
