# Generated by Django 4.2.9 on 2024-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_staff_alter_attendance_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="in_out",
            field=models.IntegerField(
                choices=[(1, "出勤（IN）"), (0, "退勤（OUT）")],
                default=None,
                verbose_name="IN/OUT",
            ),
        ),
    ]
